import type { Capability } from "@/lib/types";

/**
 * The twelve system categories. Copy is lifted from the capability index in
 * the design source; `slug`, `summary` and `icon` are additions needed for the
 * per-category routes. Order is the catalogue order and drives the `num`.
 */
export const capabilities: Capability[] = [
  {
    slug: "ai-chatbots",
    num: "01",
    name: "AI Chatbots",
    tagline: "Conversational systems that actually resolve tickets",
    summary:
      "Conversational systems grounded in your own data, escalating only when they should. Not a widget bolted onto a help centre — a resolution path with an audit trail.",
    problems: [
      "Slow support response on nights and weekends",
      "Repetitive tier-1 inquiries consuming senior time",
      "24/7 coverage gaps across regions",
      "Inconsistent answers between channels and agents",
    ],
    useCases: [
      "Order-status and returns bots",
      "Internal HR and IT assistants",
      "Multilingual support desks",
      "Inbound lead qualification",
    ],
    industries: ["retail", "finance", "healthcare", "education"],
    technologies: ["LLMs", "RAG", "LangGraph", "FastAPI", "Vector databases"],
    impact: "60–80% of tier-1 tickets deflected",
    icon: "chat",
  },
  {
    slug: "computer-vision",
    num: "02",
    name: "Computer Vision",
    tagline: "Cameras become sensors for quality, safety and count",
    summary:
      "Quality, safety and count measured continuously instead of sampled. Models run beside the line on edge hardware, so a decision never waits on a network round trip.",
    problems: [
      "Manual inspection cost scaling with volume",
      "Defects escaping to the customer undetected",
      "Safety incidents nobody witnessed",
      "Counts that cannot be verified after the fact",
    ],
    useCases: [
      "Defect detection on production lines",
      "PPE and safety-zone compliance",
      "Shelf and planogram analytics",
      "Document capture and OCR",
    ],
    industries: ["manufacturing", "retail", "construction", "agriculture"],
    technologies: ["PyTorch", "OpenCV", "NVIDIA edge GPUs", "TensorRT"],
    impact: "Defect escape rate cut by 90%+",
    icon: "vision",
  },
  {
    slug: "factory-automation",
    num: "03",
    name: "Factory Automation",
    tagline: "Software that runs the floor, not just reports on it",
    summary:
      "Machine data in, decisions out. One timeline for every signal on the floor, and the write-back path to act on what it says.",
    problems: [
      "Manual data entry from machines and clipboards",
      "Unexplained downtime with no root cause",
      "OEE that nobody trusts or can drill into",
      "Paper travellers and lost traceability",
    ],
    useCases: [
      "Line monitoring and digital andon boards",
      "Predictive maintenance",
      "Traceability and genealogy systems",
      "Changeover and OEE analytics",
    ],
    industries: ["manufacturing", "automotive", "agriculture"],
    technologies: ["OPC-UA", "Kafka", "TimescaleDB", "Python"],
    impact: "10–25% OEE improvement",
    icon: "factory",
  },
  {
    slug: "enterprise-automation",
    num: "04",
    name: "Enterprise Automation",
    tagline: "Workflows that finish themselves",
    summary:
      "Processes that run end to end with humans only at the judgment points. Every step logged, every exception routed to a person who can actually decide.",
    problems: [
      "Swivel-chair processes between systems",
      "Approval bottlenecks with no visibility",
      "Spreadsheet operations at production scale",
      "Month-end crunches that burn the team",
    ],
    useCases: [
      "Invoice and claims processing",
      "Employee onboarding flows",
      "Compliance and regulatory reporting",
      "Quote-to-cash orchestration",
    ],
    industries: ["finance", "logistics", "government", "healthcare"],
    technologies: ["Python", "Agentic AI", "RPA", "API orchestration"],
    impact: "Thousands of hours returned per year",
    icon: "automation",
  },
  {
    slug: "custom-software",
    num: "05",
    name: "Custom Software",
    tagline: "The system your business actually needs, built to fit",
    summary:
      "Built to fit the process rather than the other way around. When the off-the-shelf option would cost you more in workarounds than the build would cost outright.",
    problems: [
      "Off-the-shelf tools that fit 60% of the process",
      "Legacy lock-in with no upgrade path",
      "Integration gaps bridged by email",
      "Critical operations held together by one spreadsheet",
    ],
    useCases: [
      "Operations platforms",
      "Quoting and configuration engines",
      "Scheduling and dispatch systems",
      "Customer and partner portals",
    ],
    industries: ["manufacturing", "logistics", "finance", "construction"],
    technologies: ["React", "FastAPI", "Postgres", "Docker"],
    impact: "One system replaces five tools",
    icon: "custom",
  },
  {
    slug: "web-development",
    num: "06",
    name: "Web Development",
    tagline: "Fast, credible, measurable web presence",
    summary:
      "Engineered like a product, not decorated like a brochure. Budgets set in milliseconds, and a content model your team can actually run.",
    problems: [
      "Slow sites losing traffic before first paint",
      "Poor conversion with no instrumentation to explain it",
      "CMS sprawl across teams",
      "Agency stacks nobody in-house can maintain",
    ],
    useCases: [
      "Marketing and product sites",
      "Customer portals",
      "E-commerce storefronts",
      "Documentation platforms",
    ],
    industries: ["retail", "finance", "education", "healthcare"],
    technologies: ["Next.js", "React", "Vercel", "Headless CMS"],
    impact: "Sub-second loads, higher conversion",
    icon: "web",
  },
  {
    slug: "mobile-apps",
    num: "07",
    name: "Mobile Apps",
    tagline: "Your operation in every pocket",
    summary:
      "Online or off. Field teams capture at the point of work, and the sync layer reconciles when signal returns rather than losing the entry.",
    problems: [
      "Field teams working blind between depots",
      "Paper forms re-keyed days later",
      "No push visibility into live operations",
      "Dead zones that break connected-only tools",
    ],
    useCases: [
      "Field service and inspection apps",
      "Machine-operator companions",
      "Customer-facing apps",
      "Barcode and asset capture",
    ],
    industries: ["logistics", "construction", "healthcare", "retail"],
    technologies: ["React Native", "Offline-first sync", "Push infrastructure"],
    impact: "Field data latency: days → minutes",
    icon: "mobile",
  },
  {
    slug: "saas-products",
    num: "08",
    name: "SaaS Products",
    tagline: "From idea to billing customers",
    summary:
      "Multi-tenant from the first commit, because retrofitting tenancy costs more than building it. Billing, metering and isolation designed in, not bolted on.",
    problems: [
      "MVP cycles measured in quarters",
      "Prototypes that cannot scale past pilot",
      "No tenancy or billing model",
      "Internal tools with no path to product",
    ],
    useCases: [
      "B2B vertical SaaS",
      "Internal tools productized",
      "Usage-billed platforms",
      "Machine-builder service portals",
    ],
    industries: ["manufacturing", "logistics", "finance", "education"],
    technologies: ["Next.js", "Postgres", "Stripe", "Kubernetes"],
    impact: "MVP in weeks, not quarters",
    icon: "saas",
  },
  {
    slug: "data-platforms",
    num: "09",
    name: "Data Platforms",
    tagline: "One truth across every system",
    summary:
      "Pipelines, warehouse and the dashboards on top — with lineage, so a number in the boardroom can be traced back to the sensor that produced it.",
    problems: [
      "Siloed data across departments",
      "Manual reporting cycles",
      "Numbers nobody trusts enough to act on",
      "Dashboards that are a week behind reality",
    ],
    useCases: [
      "Warehouses and lakehouses",
      "Streaming pipelines",
      "Executive dashboards",
      "ML feature stores",
    ],
    industries: ["finance", "manufacturing", "retail", "education"],
    technologies: ["Kafka", "dbt", "Azure", "AWS", "Snowflake"],
    impact: "Reporting time: days → real time",
    icon: "data",
  },
  {
    slug: "llm-applications",
    num: "10",
    name: "LLM Applications",
    tagline: "Language models wired into real workflows",
    summary:
      "With citations and guardrails, because an unsourced answer is not an answer in a regulated process. Retrieval you can inspect and evaluation you can repeat.",
    problems: [
      "Knowledge locked in unsearchable documents",
      "Slow drafting of repetitive deliverables",
      "Review load falling on the most senior people",
      "Tribal knowledge leaving with the person",
    ],
    useCases: [
      "Contract and policy analysis",
      "Report and proposal drafting",
      "Semantic search over archives",
      "Meeting and call intelligence",
    ],
    industries: ["finance", "healthcare", "government", "education"],
    technologies: ["LLMs", "RAG", "Vector DBs", "MCP"],
    impact: "Document work 5–10× faster",
    icon: "llm",
  },
  {
    slug: "agentic-ai",
    num: "11",
    name: "Agentic AI",
    tagline: "Systems that plan, act and verify — not just answer",
    summary:
      "Whole processes run end to end. The agent proposes, the tools execute, and a verification step catches what a single model pass would miss.",
    problems: [
      "Multi-step processes needing judgment at each step",
      "Work that does not fit rigid RPA scripts",
      "Handoffs where context is lost every time",
      "Exception queues that only grow",
    ],
    useCases: [
      "Procurement and sourcing agents",
      "Research and diligence agents",
      "Operations copilots",
      "Quoting agents with human sign-off",
    ],
    industries: ["logistics", "finance", "manufacturing", "government"],
    technologies: [
      "LangGraph",
      "MCP",
      "Tool-use LLMs",
      "Human-in-the-loop review",
    ],
    impact: "Whole processes run unattended",
    icon: "agent",
  },
  {
    slug: "api-integrations",
    num: "12",
    name: "API Integrations",
    tagline: "Your systems, finally talking to each other",
    summary:
      "Reliably, with retries and receipts. Idempotent by design, so a replayed message never double-charges or double-ships.",
    problems: [
      "Double entry between systems of record",
      "Silent sync errors discovered at audit",
      "Vendor silos with no export path",
      "Brittle point-to-point scripts nobody owns",
    ],
    useCases: [
      "ERP ↔ CRM synchronisation",
      "Payment and settlement rails",
      "Partner and EDI APIs",
      "Webhook infrastructure",
    ],
    industries: ["logistics", "finance", "retail", "manufacturing"],
    technologies: [
      "FastAPI",
      "Message queues",
      "Webhooks",
      "Idempotent design",
    ],
    impact: "Zero re-keying between systems",
    icon: "api",
  },
];
